# scripts/create_issue.py  （旧 open_issue.py を改名）
import argparse, subprocess, sys, textwrap, datetime, pathlib, os

def main():
    ap = argparse.ArgumentParser(description="Create GitHub Issue via gh")
    ap.add_argument("title", help="Issue title")
    ap.add_argument("-b", "--body", help="Body text (inline)")
    ap.add_argument("-f", "--file", help="Body markdown path")
    args = ap.parse_args()

    if args.file:
        body = pathlib.Path(args.file).read_text(encoding="utf8")
    elif args.body:
        body = args.body
    else:
        # 簡易モード: 直近ログ100行 + テンプレ
        log = pathlib.Path("logs/last_fail.log").read_text(encoding="utf8")[-4000:] \
              if pathlib.Path("logs/last_fail.log").exists() else "ログなし"
        body = textwrap.dedent(f"""
        <!-- Auto-generated by Claude Code -->
        **Timestamp (UTC)**: {datetime.datetime.utcnow().isoformat()}Z

        ```
        {log}
        ```

        _Feel free to add extra context!_
        """)

    subprocess.run([
        "gh", "issue", "create",
        "--title", args.title,
        "--body",  body,
    ], check=True)

if __name__ == "__main__":
    main()